import { useEffect, useState, useRef } from "react";

import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import css from "../../../styles/me.settings.module.css";
import { Bell2Icon, BellIcon, BookmarkCurvedIcon, MediumLogo, MediumNamedIcon, SearchIcon } from "../../../assets/icon/medium-icons";

import avatar from "../../../assets/image/avatars/avatar-1.jpg";

const footerData = [
  {text: 'Help', href: ''},
  {text: 'Status', href: ''},
  {text: 'Writers', href: ''},
  {text: 'Blog', href: ''},
  {text: 'Careers', href: ''},
  {text: 'Privacy', href: ''},
  {text: 'Terms', href: ''},
  {text: 'About', href: ''},

]


export default function Home() {
  const [isSticky, setIsSticky] = useState(false);
  const navRef = useRef();
  const [scrollTop, setScrollTop] = useState(0);

  const [isEditing, setIsEditing] = useState(false);

  useEffect(()=>{
     window.onscroll = () => {
      const scroll = window.scrollY ;
      setScrollTop(scroll)
    }
  }, [navRef])

  useEffect(() => {
    if(scrollTop >= 40) {
      setIsSticky(true)
    }
    else {
      setIsSticky(false)
    }
  }, [scrollTop])



  return (
    <div className={css.container}>
      <Head>
        <title>clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={css.site_wrapper}>

        {/* ======= HEADER ======= */}

        <div className={css.header}>
          <div className={css.content}>
            <div className={css.metabar}>
              <div className={css.shortLogo}>
                <MediumLogo />
              </div>
              <div className={css.fullLogo}>
                <MediumNamedIcon />
              </div>
            </div>
            <div className={css.metabar}>
              <label htmlFor="search">
                <div className={css.icon}> <SearchIcon />  </div>
                <input type="text" id="search" />
              </label>
              <Link href={'/search'}>
                <a className={`${css.link} ${css.search}`}>
                  <span className={css.icon}> <SearchIcon /> </span>
                </a>
              </Link>
              <Link href={'/me/lists'}>
                <a className={`${css.link} ${css.bookmark}`}>
                  <span className={css.icon}> <BookmarkCurvedIcon/> </span>
                </a>
              </Link>
              <button className={css.btn}>
                <span className={css.icon}> <Bell2Icon/> </span>
              </button>
              <Link href={'/membership'}>
                <a className={`${css.link} ${css.upgrade}`}>
                  Upgrade
                </a>
              </Link>
              <button className={css.btn}>
                <div className={css.avatar}> 
                  <Image src={avatar} layout='fill' />
                </div>
              </button>

            </div>
          </div>
      
        </div>

        {/* ========== MAIN ========== */}

        <div className={css.settings}>
            <div className={css.settingsNav}>
              <div className={`${css.nav} ${isSticky ? css.stickyNav :''}`} ref={navRef} >
                <div className={css.title}> Settings </div>
                <ul>
                  <li>
                    <div className={css.text}>
                      <span> About you </span>
                    </div>
                  </li>
                  <li>
                    <div className={css.text}>
                      <span> Design </span>
                    </div>
                  </li>
                  <li>
                    <div className={css.text}>
                      <span> Audience development </span>
                    </div>
                  </li>
                  <li>
                    <div className={css.text}>
                      <span> Email settings </span>
                    </div>
                  </li>
                  <li>
                    <div className={css.text}>
                      <span> Connections </span>
                    </div>
                  </li>
                  <li>
                    <div className={css.text}>
                      <span> Accounts </span>
                    </div>
                  </li>
                  <li>
                    <div className={css.text}>
                      <span> Membership </span>
                    </div>
                  </li>
                  <li>
                    <div className={css.text}>
                      <span> Integration tokens </span>
                    </div>
                  </li>
                  <li>
                    <div className={css.text}>
                      <span> Security </span>
                    </div>
                  </li>
                </ul>
                <footer className={css.footer}>
                  <div className={css.items_list}>
                     {footerData.map((item, index) => {
                       const {text, href} = item ;
                       return (
                        <Link href={href}>
                          <a className={css.link}> {text} </a>
                        </Link>
                       )
                     })}
                  </div>
                </footer>
              </div>
            </div>

            <div className={css.settingsMain}>

              {/* ======== ABOUT YOU SECTION ======== */}
              <div className={css.section}>
                
                <header className={css.heading}> 
                  <div className={css.heading_content}> 
                    <h2> About you </h2> 
                  </div>
                </header>

                {/* ======== USER NAME ======= */}
                
                <li className={css.listItem}>
                  <div className={css.listItem_content}>
                    <div className={css.title}> Name </div>
                    <div className={css.body}>
                      <input type="text" value={'Aman Ghanghoriya'} disabled={isEditing ? false : true} />  
                      <div className={css.text}>
                        Your name appears on your Profile page, as your byline, and in your responses. It is a required field.
                      </div>
                    </div>
                  </div>
                  <div className={css.listItem_control}>
                    {isEditing ? 
                      (<div className={css.btnSet}>
                        <button className={`${css.btn} ${css.save}`} onClick={() => setIsEditing(false)} > Save  </button>
                        <button className={`${css.btn} ${css.cancel}`} onClick={() => setIsEditing(false)} > Cancel  </button> 
                      </div>) : (
                        <button className={`${css.btn} ${css.edit}`} onClick={() => setIsEditing(true)} > Edit  </button>
                      ) 
                    }
                  </div>
                </li>

                {/* ============ USER BIO =========== */}

                <li className={css.listItem}>
                  <div className={css.listItem_content}>
                    <div className={css.title}> Short bio </div>
                    <div className={css.body}>
                      <input type="text" value={'Programmer'} disabled={isEditing ? false : true} />  
                      <div className={css.text}>
                        Your short bio appears on your Profile and next to your stories. Max 160 characters.
                      </div>
                    </div>
                  </div>
                  <div className={css.listItem_control}>
                    {isEditing ? 
                      (<div className={css.btnSet}>
                        <button className={`${css.btn} ${css.save}`} onClick={() => setIsEditing(false)} > Save  </button>
                        <button className={`${css.btn} ${css.cancel}`} onClick={() => setIsEditing(false)} > Cancel  </button> 
                      </div>) : (
                        <button className={`${css.btn} ${css.edit}`} onClick={() => setIsEditing(true)} > Edit  </button>
                      ) 
                    }
                  </div>
                </li>

                {/* ============ Photo =========== */}

                <li className={css.listItem}>
                  <div className={css.listItem_content}>
                    <div className={css.title}> Photo </div>
                    <div className={css.body}>
                      <div className={css.text}>
                        Your photo appears on your Profile page and with your stories across Medium.
                        <br /><br/>
                        Recommended size: Square, at least 1000 pixels per side. File type: JPG, PNG or GIF.
                      </div>
                    </div>
                  </div>
                  <div className={css.listItem_control}>
                    {isEditing ? 
                      (<div className={css.btnSet}>
                        <button className={`${css.btn} ${css.save}`} onClick={() => setIsEditing(false)} > Save  </button>
                        <button className={`${css.btn} ${css.cancel}`} onClick={() => setIsEditing(false)} > Cancel  </button> 
                      </div>) : (
                        <button className={`${css.btn} ${css.edit}`} onClick={() => setIsEditing(true)} > Edit  </button>
                      ) 
                    }
                  </div>
                </li>        

                {/* About page redirect  */}

                <li className={css.listItem}>
                  <div className={css.listItem_content}>
                    <div className={css.title}> About page </div>
                    <div className={css.body}>
                      <div className={css.text}>
                        This page should tell your readers more about you and explain the benefits of reading your work.
                      </div>
                    </div>
                  </div>
                  <div className={css.listItem_control}>
                    {isEditing ? 
                      (<div className={css.btnSet}>
                        <button className={`${css.btn} ${css.save}`} onClick={() => setIsEditing(false)} > Save  </button>
                        <button className={`${css.btn} ${css.cancel}`} onClick={() => setIsEditing(false)} > Cancel  </button> 
                      </div>) : (
                        <button className={`${css.btn} ${css.edit}`} onClick={() => setIsEditing(true)} > Edit  </button>
                      ) 
                    }
                  </div>
                </li>          


                {/* ============ Photo =========== */}

                <li className={`${css.listItem} ${css.username}`}>
                  <div className={css.listItem_content}>
                    <div className={css.title}> Username {"&"} URL </div>
                    <div className={css.body}>
                      <table>
                        <tbody>
                          <tr>
                            <td> <span> Username </span> </td>
                            <td>
                              <input type="text" className={css.url_input} value={'amanghanghoriya2@gmail.com'} />
                            </td>
                          </tr>
                          <tr>
                            <td> </td>
                            <td> </td>
                          </tr>
                          <tr>
                            <td> <span> URL </span> </td>
                            <td>
                              https://medium.com/@amanghanghoriya2
                            </td>
                          </tr>
                        </tbody>
                      </table>

                    </div>
                  </div>
                  <div className={css.listItem_control}>
                    {isEditing ? 
                      (<div className={css.btnSet}>
                        <button className={`${css.btn} ${css.save}`} onClick={() => setIsEditing(false)} > Save  </button>
                        <button className={`${css.btn} ${css.cancel}`} onClick={() => setIsEditing(false)} > Cancel  </button> 
                      </div>) : (
                        <button className={`${css.btn} ${css.edit}`} onClick={() => setIsEditing(true)} > Edit  </button>
                      ) 
                    }
                  </div>
                </li>      

              </div>


              {/* ======== EMAIL SECTION ============= */}
              <div className={`${css.section} ${css.email}`}>
                
                <header className={css.heading}> 
                  <div className={css.heading_content}> 
                    <h2> Email settings </h2> 
                  </div>
                </header>

                {/* ======== USER NAME ======= */}
                
                <li className={css.listItem}>
                  <div className={css.listItem_content}>
                    <div className={css.title}> Your email </div>
                    <div className={css.body}>
                      <input type="text" value={'amanghanghoriya2@gmail.com'} disabled={isEditing ? false : true} />  
                    </div>
                  </div>
                  <div className={css.listItem_control}>
                    {isEditing ? 
                      (<div className={css.btnSet}>
                        <button className={`${css.btn} ${css.save}`} onClick={() => setIsEditing(false)} > Save  </button>
                        <button className={`${css.btn} ${css.cancel}`} onClick={() => setIsEditing(false)} > Cancel  </button> 
                      </div>) : (
                        <button className={`${css.btn} ${css.edit}`} onClick={() => setIsEditing(true)} > Edit email  </button>
                      ) 
                    }
                  </div>
                </li>


              </div>

              
              {/* SECURITY SECTION */}
              <div className={css.section}>
                <header className={css.heading}> 
                  <div className={css.heading_content}> 
                    <h2> Security </h2> 
                  </div>
                </header>

                {/* ======== deactivate ======= */}
                
                <li className={css.listItem}>
                  <div className={css.listItem_content}>
                    <div className={css.title}> Deactive account </div>
                    <div className={css.body}>
                      <div className={css.text}>
                          Deactivating your account will remove it from Medium within a few minutes. Deactivation will also immediately cancel any subscription for Medium Membership, and no money will be reimbursed. You can sign back in anytime to reactivate your account and restore its content.
                          <button className={`${css.btn} ${css.danger}`}>
                            Deactivate account
                          </button>
                      </div>
                    </div>
                  </div>
                </li>

                {/* =========== DELETE =========== */}
                <li className={css.listItem}>
                  <div className={css.listItem_content}>
                    <div className={css.title}> Deactive account </div>
                    <div className={css.body}>
                      <div className={css.text}>
                          Permanently delete your account and all of your content.
                          <button className={`${css.btn} ${css.danger}`}>
                            Deactivate account
                          </button>
                      </div>
                    </div>
                  </div>
                </li>

              </div>

            </div>
        </div>

      </div>


    </div>
  );
}



