import { useEffect, useState } from "react";

import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import css from "../styles/home.module.css";
import Navbar from "./Navbar";

import { trending_stories } from "../assets/data/trending";
import { suggested_stories } from "../assets/data/suggested";

import topics from "../assets/data/topics";

import { useDispatch, useSelector } from "react-redux";
import { setIsSigninDialog } from "../features/app/appSlice";
import SigninDialog from "./dialogs/signin/Dialog";


export default function Home() {
  const [isResize, setIsResize] = useState(0);
  const {isSigninDialog} = useSelector((state) => state.app);

  useEffect(() => {
    const ele = document.querySelector("#discover_topic");
    let threshold = window.pageYOffset + ele.getBoundingClientRect().top - 60;

    if (window.pageYOffset < 902) {
      ele.style.position = "relative";
      ele.style.top = 0;
    } else {
      window.onscroll = (e) => {
        let top = 0;
        if (window.scrollY > threshold) {
          console.log("Threshold crossed");
          top = window.scrollY - threshold;
          ele.style.top = `${top}px`;
        }
      };
    }
  }, [isResize]);

  useEffect(() => {
    window.onresize = (e) => {
      setIsResize(window.scrollY);
    };
  }, []);

  return (
    <>
      <Head>
        <title>clone - Where good ideas find you </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`${css.container} ${isSigninDialog ? css.dialog : ''}`}>

        {isSigninDialog ? <SigninDialog /> : ""}

        <Navbar />

        <Hero />

        <TrendingStories />

        <Suggested />

      </div>

    </>
  );
}

const Hero = () => {
  const dispatch = useDispatch();

  return (
    <section className={`section ${css.hero_s}`}>
      <div className={`section-inner ${css.hero_s_inner}`}>
        <div className="grid">
          <div className={css.left}>
            <h1>Stay curious.</h1>
            <p>
              Discover stories, thinking, and expertise from writers on any
              topic.
            </p>
            <div>
              <button className={css.btn} onClick={() => dispatch(setIsSigninDialog(true))}> Start reading </button>
            </div>
          </div>
          <div className={css.right}></div>
        </div>
      </div>
    </section>
  );
};

const TrendingStories = () => {
  return (
    <section className={`section ${css.trending_s}`}>
      <div className={`section-inner ${css.trending_s_inner}`}>
        <div className="grid">
          <div className={css.heading}>
            <h4> trending on medium </h4>
          </div>
          <div className={css.stories}>
            {trending_stories.map((story, index) => {
              const { id, avatar, title, duration, date, author } = story;
              return (
                <div className={css.story} key={index}>
                  <div className={css.sno}> {id} </div>
                  <div className={css.content}>
                    <div className={css.author}>
                      <Link href={"/@author"}>
                        <a>
                          <div className={css.avatar}>
                            <Image src={avatar} alt={author} layout="fill" />
                          </div>
                        </a>
                      </Link>
                      <Link href={"/@author"}>
                        <a>
                          <span> {author} </span>
                        </a>
                      </Link>
                    </div>
                    <h3>
                      <Link href={"/@author/story-titile"}>{title}</Link>
                    </h3>
                    <div className={css.footer}>
                      <span> {date} </span>
                      <span className={css.dot}> · </span>
                      <span> {duration} read</span>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </section>
  );
};

const Suggested = () => {
  return (
    <section className={`section ${css.suggested_s}`}>
      <div className={`section-inner ${css.suggested_s_inner}`}>
        <div className={`grid ${css.grid}`}>
          <div className={css.stories}>
            {suggested_stories.map((story, index) => {
              const {
                id,
                avatar,
                author,
                topic,
                thumbnail,
                title,
                text,
                duration,
                date,
              } = story;
              return (
                <div className={css.story} key={index}>
                  <div className={css.content}>
                    <div className={css.author}>
                      <div className={css.avatar}>
                        <Link href={"/@author"}>
                          <a>
                            <Image src={avatar} alt={author} layout="fill" />
                          </a>
                        </Link>
                      </div>
                      <div>
                        <Link href={"/@author"}>{author}</Link>
                      </div>
                    </div>
                    <Link
                      href={
                        "/@author/" + title.replaceAll(" ", "+").toLowerCase()
                      }
                    >
                      <a>
                        <h3>{title}</h3>
                        <p> {text} </p>
                      </a>
                    </Link>
                    <div className={css.footer}>
                      <span> {date} </span>
                      <span className={css.dot}> · </span>
                      <span> {duration} read</span>
                      <span className={css.dot}> · </span>
                      <Link href={"/tag/" + topic}>
                        <a>
                          <span className={css.topic}> {topic} </span>
                        </a>
                      </Link>
                    </div>
                  </div>
                  <div className={css.thumbnail}>
                    <Link
                      href={
                        "/@author/" + title.replaceAll(" ", "+").toLowerCase()
                      }
                    >
                      <a>
                        <Image src={thumbnail} alt="thumbnail" layout="fill" />
                      </a>
                    </Link>
                  </div>
                </div>
              );
            })}
          </div>
          <div className={css.discover} id="discover_topic">
            <h4> discover more of what matters to you</h4>
            <div className={css.wrapper}>
              {topics.map((topic, index) => {
                return (
                  <Link href={"/tag/" + topic}>
                    <a>
                      <div className={css.topic} key={index}>
                        {topic}
                      </div>
                    </a>
                  </Link>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
