import { useEffect, useState } from "react";

import Head from "next/head";

import Layout from "./Layout";
import Rightbar from "./rightbar/me/Rightbar";
import Main from "./main/me/home/Main";

export default function MeHome() {
  return (
    <>
      <Head>
        <title>clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Main />
        <Rightbar />

      </Layout>
    </>
  );
}
