import PageLayout from "../components/Layout";

import Head from "next/head";

export default function () {
  return (
    <>
      <Head>
        <title>clone - layout </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout>

      </PageLayout>
      
    </>
  );
}
