import Head from "next/head";


import Layout from "../../../components/Layout";
import Rightbar from "../../../components/rightbar/me/Rightbar";
import Main from "../../../components/main/me/stories/Main";


export default function () {
  return (
    <>
      <Head>
        <title> Your stories - Clone </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Main />
        <Rightbar />
      </Layout>
    </>
  );
}
